### ISSUE TITLE
file-loader module issue

### ISSUE THREAD

**Issue by MfundoVala** [enderh3art/Ramen-Shop#5]
hey great project! i'm getting this error when running the project, it seems the file-loader module is having issues playing sounds
using node v18.4.0

ERROR in ./static/sounds/bloop.mp3
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at getHashDigest (/Users/thenewowner/Documents/Ramen-Shop/node_modules/file-loader/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /Users/thenewowner/Documents/Ramen-Shop/node_modules/file-loader/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/Users/thenewowner/Documents/Ramen-Shop/node_modules/file-loader/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/Users/thenewowner/Documents/Ramen-Shop/node_modules/file-loader/dist/index.js:29:48)

**Comment by mathalav55** [comment]
same here did you find any resolution?

**Comment by LeeDeea** [comment]
just open http://localhost:8080

**Comment by LeeDeea** [comment]
just open http://localhost:8080 after npm run dev

**Comment by LeeDeea** [comment]
> same here did you find any solution?

just open http://localhost:8080/ after npm run dev

**Comment by jerung669** [comment]
can i ask, how to change name of jesse zhou at shop banner and also floor?? which one source code that ineed to find out? thanks

**Comment by voidjay** [comment]
i use node v16.20.1 can run project success
